//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Function.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProcessingGuarantees int32

const (
	ProcessingGuarantees_ATLEAST_ONCE     ProcessingGuarantees = 0
	ProcessingGuarantees_ATMOST_ONCE      ProcessingGuarantees = 1
	ProcessingGuarantees_EFFECTIVELY_ONCE ProcessingGuarantees = 2
)

var ProcessingGuarantees_name = map[int32]string{
	0: "ATLEAST_ONCE",
	1: "ATMOST_ONCE",
	2: "EFFECTIVELY_ONCE",
}
var ProcessingGuarantees_value = map[string]int32{
	"ATLEAST_ONCE":     0,
	"ATMOST_ONCE":      1,
	"EFFECTIVELY_ONCE": 2,
}

func (x ProcessingGuarantees) String() string {
	return proto.EnumName(ProcessingGuarantees_name, int32(x))
}
func (ProcessingGuarantees) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{0}
}

type SubscriptionType int32

const (
	SubscriptionType_SHARED   SubscriptionType = 0
	SubscriptionType_FAILOVER SubscriptionType = 1
)

var SubscriptionType_name = map[int32]string{
	0: "SHARED",
	1: "FAILOVER",
}
var SubscriptionType_value = map[string]int32{
	"SHARED":   0,
	"FAILOVER": 1,
}

func (x SubscriptionType) String() string {
	return proto.EnumName(SubscriptionType_name, int32(x))
}
func (SubscriptionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{1}
}

type SubscriptionPosition int32

const (
	SubscriptionPosition_LATEST   SubscriptionPosition = 0
	SubscriptionPosition_EARLIEST SubscriptionPosition = 1
)

var SubscriptionPosition_name = map[int32]string{
	0: "LATEST",
	1: "EARLIEST",
}
var SubscriptionPosition_value = map[string]int32{
	"LATEST":   0,
	"EARLIEST": 1,
}

func (x SubscriptionPosition) String() string {
	return proto.EnumName(SubscriptionPosition_name, int32(x))
}
func (SubscriptionPosition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{2}
}

type FunctionState int32

const (
	FunctionState_RUNNING FunctionState = 0
	FunctionState_STOPPED FunctionState = 1
)

var FunctionState_name = map[int32]string{
	0: "RUNNING",
	1: "STOPPED",
}
var FunctionState_value = map[string]int32{
	"RUNNING": 0,
	"STOPPED": 1,
}

func (x FunctionState) String() string {
	return proto.EnumName(FunctionState_name, int32(x))
}
func (FunctionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{3}
}

type FunctionDetails_Runtime int32

const (
	FunctionDetails_JAVA   FunctionDetails_Runtime = 0
	FunctionDetails_PYTHON FunctionDetails_Runtime = 1
	FunctionDetails_GO     FunctionDetails_Runtime = 3
)

var FunctionDetails_Runtime_name = map[int32]string{
	0: "JAVA",
	1: "PYTHON",
	3: "GO",
}
var FunctionDetails_Runtime_value = map[string]int32{
	"JAVA":   0,
	"PYTHON": 1,
	"GO":     3,
}

func (x FunctionDetails_Runtime) String() string {
	return proto.EnumName(FunctionDetails_Runtime_name, int32(x))
}
func (FunctionDetails_Runtime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{2, 0}
}

type FunctionDetails_ComponentType int32

const (
	FunctionDetails_UNKNOWN  FunctionDetails_ComponentType = 0
	FunctionDetails_FUNCTION FunctionDetails_ComponentType = 1
	FunctionDetails_SOURCE   FunctionDetails_ComponentType = 2
	FunctionDetails_SINK     FunctionDetails_ComponentType = 3
)

var FunctionDetails_ComponentType_name = map[int32]string{
	0: "UNKNOWN",
	1: "FUNCTION",
	2: "SOURCE",
	3: "SINK",
}
var FunctionDetails_ComponentType_value = map[string]int32{
	"UNKNOWN":  0,
	"FUNCTION": 1,
	"SOURCE":   2,
	"SINK":     3,
}

func (x FunctionDetails_ComponentType) String() string {
	return proto.EnumName(FunctionDetails_ComponentType_name, int32(x))
}
func (FunctionDetails_ComponentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{2, 1}
}

type Resources struct {
	Cpu                  float64  `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram                  int64    `protobuf:"varint,2,opt,name=ram,proto3" json:"ram,omitempty"`
	Disk                 int64    `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{0}
}
func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (dst *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(dst, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetCpu() float64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *Resources) GetRam() int64 {
	if m != nil {
		return m.Ram
	}
	return 0
}

func (m *Resources) GetDisk() int64 {
	if m != nil {
		return m.Disk
	}
	return 0
}

type RetryDetails struct {
	MaxMessageRetries    int32    `protobuf:"varint,1,opt,name=maxMessageRetries,proto3" json:"maxMessageRetries,omitempty"`
	DeadLetterTopic      string   `protobuf:"bytes,2,opt,name=deadLetterTopic,proto3" json:"deadLetterTopic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryDetails) Reset()         { *m = RetryDetails{} }
func (m *RetryDetails) String() string { return proto.CompactTextString(m) }
func (*RetryDetails) ProtoMessage()    {}
func (*RetryDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{1}
}
func (m *RetryDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryDetails.Unmarshal(m, b)
}
func (m *RetryDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryDetails.Marshal(b, m, deterministic)
}
func (dst *RetryDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryDetails.Merge(dst, src)
}
func (m *RetryDetails) XXX_Size() int {
	return xxx_messageInfo_RetryDetails.Size(m)
}
func (m *RetryDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryDetails.DiscardUnknown(m)
}

var xxx_messageInfo_RetryDetails proto.InternalMessageInfo

func (m *RetryDetails) GetMaxMessageRetries() int32 {
	if m != nil {
		return m.MaxMessageRetries
	}
	return 0
}

func (m *RetryDetails) GetDeadLetterTopic() string {
	if m != nil {
		return m.DeadLetterTopic
	}
	return ""
}

type FunctionDetails struct {
	Tenant               string                        `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Namespace            string                        `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string                        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClassName            string                        `protobuf:"bytes,4,opt,name=className,proto3" json:"className,omitempty"`
	LogTopic             string                        `protobuf:"bytes,5,opt,name=logTopic,proto3" json:"logTopic,omitempty"`
	ProcessingGuarantees ProcessingGuarantees          `protobuf:"varint,6,opt,name=processingGuarantees,proto3,enum=proto.ProcessingGuarantees" json:"processingGuarantees,omitempty"`
	UserConfig           string                        `protobuf:"bytes,7,opt,name=userConfig,proto3" json:"userConfig,omitempty"`
	SecretsMap           string                        `protobuf:"bytes,16,opt,name=secretsMap,proto3" json:"secretsMap,omitempty"`
	Runtime              FunctionDetails_Runtime       `protobuf:"varint,8,opt,name=runtime,proto3,enum=proto.FunctionDetails_Runtime" json:"runtime,omitempty"`
	AutoAck              bool                          `protobuf:"varint,9,opt,name=autoAck,proto3" json:"autoAck,omitempty"`
	Parallelism          int32                         `protobuf:"varint,10,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	Source               *SourceSpec                   `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	Sink                 *SinkSpec                     `protobuf:"bytes,12,opt,name=sink,proto3" json:"sink,omitempty"`
	Resources            *Resources                    `protobuf:"bytes,13,opt,name=resources,proto3" json:"resources,omitempty"`
	PackageUrl           string                        `protobuf:"bytes,14,opt,name=packageUrl,proto3" json:"packageUrl,omitempty"`
	RetryDetails         *RetryDetails                 `protobuf:"bytes,15,opt,name=retryDetails,proto3" json:"retryDetails,omitempty"`
	RuntimeFlags         string                        `protobuf:"bytes,17,opt,name=runtimeFlags,proto3" json:"runtimeFlags,omitempty"`
	ComponentType        FunctionDetails_ComponentType `protobuf:"varint,18,opt,name=componentType,proto3,enum=proto.FunctionDetails_ComponentType" json:"componentType,omitempty"`
	CustomRuntimeOptions string                        `protobuf:"bytes,19,opt,name=customRuntimeOptions,proto3" json:"customRuntimeOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *FunctionDetails) Reset()         { *m = FunctionDetails{} }
func (m *FunctionDetails) String() string { return proto.CompactTextString(m) }
func (*FunctionDetails) ProtoMessage()    {}
func (*FunctionDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{2}
}
func (m *FunctionDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionDetails.Unmarshal(m, b)
}
func (m *FunctionDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionDetails.Marshal(b, m, deterministic)
}
func (dst *FunctionDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionDetails.Merge(dst, src)
}
func (m *FunctionDetails) XXX_Size() int {
	return xxx_messageInfo_FunctionDetails.Size(m)
}
func (m *FunctionDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionDetails.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionDetails proto.InternalMessageInfo

func (m *FunctionDetails) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *FunctionDetails) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *FunctionDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionDetails) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *FunctionDetails) GetLogTopic() string {
	if m != nil {
		return m.LogTopic
	}
	return ""
}

func (m *FunctionDetails) GetProcessingGuarantees() ProcessingGuarantees {
	if m != nil {
		return m.ProcessingGuarantees
	}
	return ProcessingGuarantees_ATLEAST_ONCE
}

func (m *FunctionDetails) GetUserConfig() string {
	if m != nil {
		return m.UserConfig
	}
	return ""
}

func (m *FunctionDetails) GetSecretsMap() string {
	if m != nil {
		return m.SecretsMap
	}
	return ""
}

func (m *FunctionDetails) GetRuntime() FunctionDetails_Runtime {
	if m != nil {
		return m.Runtime
	}
	return FunctionDetails_JAVA
}

func (m *FunctionDetails) GetAutoAck() bool {
	if m != nil {
		return m.AutoAck
	}
	return false
}

func (m *FunctionDetails) GetParallelism() int32 {
	if m != nil {
		return m.Parallelism
	}
	return 0
}

func (m *FunctionDetails) GetSource() *SourceSpec {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *FunctionDetails) GetSink() *SinkSpec {
	if m != nil {
		return m.Sink
	}
	return nil
}

func (m *FunctionDetails) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *FunctionDetails) GetPackageUrl() string {
	if m != nil {
		return m.PackageUrl
	}
	return ""
}

func (m *FunctionDetails) GetRetryDetails() *RetryDetails {
	if m != nil {
		return m.RetryDetails
	}
	return nil
}

func (m *FunctionDetails) GetRuntimeFlags() string {
	if m != nil {
		return m.RuntimeFlags
	}
	return ""
}

func (m *FunctionDetails) GetComponentType() FunctionDetails_ComponentType {
	if m != nil {
		return m.ComponentType
	}
	return FunctionDetails_UNKNOWN
}

func (m *FunctionDetails) GetCustomRuntimeOptions() string {
	if m != nil {
		return m.CustomRuntimeOptions
	}
	return ""
}

type ConsumerSpec struct {
	SchemaType           string                          `protobuf:"bytes,1,opt,name=schemaType,proto3" json:"schemaType,omitempty"`
	SerdeClassName       string                          `protobuf:"bytes,2,opt,name=serdeClassName,proto3" json:"serdeClassName,omitempty"`
	IsRegexPattern       bool                            `protobuf:"varint,3,opt,name=isRegexPattern,proto3" json:"isRegexPattern,omitempty"`
	ReceiverQueueSize    *ConsumerSpec_ReceiverQueueSize `protobuf:"bytes,4,opt,name=receiverQueueSize,proto3" json:"receiverQueueSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ConsumerSpec) Reset()         { *m = ConsumerSpec{} }
func (m *ConsumerSpec) String() string { return proto.CompactTextString(m) }
func (*ConsumerSpec) ProtoMessage()    {}
func (*ConsumerSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{3}
}
func (m *ConsumerSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerSpec.Unmarshal(m, b)
}
func (m *ConsumerSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerSpec.Marshal(b, m, deterministic)
}
func (dst *ConsumerSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerSpec.Merge(dst, src)
}
func (m *ConsumerSpec) XXX_Size() int {
	return xxx_messageInfo_ConsumerSpec.Size(m)
}
func (m *ConsumerSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerSpec proto.InternalMessageInfo

func (m *ConsumerSpec) GetSchemaType() string {
	if m != nil {
		return m.SchemaType
	}
	return ""
}

func (m *ConsumerSpec) GetSerdeClassName() string {
	if m != nil {
		return m.SerdeClassName
	}
	return ""
}

func (m *ConsumerSpec) GetIsRegexPattern() bool {
	if m != nil {
		return m.IsRegexPattern
	}
	return false
}

func (m *ConsumerSpec) GetReceiverQueueSize() *ConsumerSpec_ReceiverQueueSize {
	if m != nil {
		return m.ReceiverQueueSize
	}
	return nil
}

type ConsumerSpec_ReceiverQueueSize struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumerSpec_ReceiverQueueSize) Reset()         { *m = ConsumerSpec_ReceiverQueueSize{} }
func (m *ConsumerSpec_ReceiverQueueSize) String() string { return proto.CompactTextString(m) }
func (*ConsumerSpec_ReceiverQueueSize) ProtoMessage()    {}
func (*ConsumerSpec_ReceiverQueueSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{3, 0}
}
func (m *ConsumerSpec_ReceiverQueueSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerSpec_ReceiverQueueSize.Unmarshal(m, b)
}
func (m *ConsumerSpec_ReceiverQueueSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerSpec_ReceiverQueueSize.Marshal(b, m, deterministic)
}
func (dst *ConsumerSpec_ReceiverQueueSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerSpec_ReceiverQueueSize.Merge(dst, src)
}
func (m *ConsumerSpec_ReceiverQueueSize) XXX_Size() int {
	return xxx_messageInfo_ConsumerSpec_ReceiverQueueSize.Size(m)
}
func (m *ConsumerSpec_ReceiverQueueSize) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerSpec_ReceiverQueueSize.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerSpec_ReceiverQueueSize proto.InternalMessageInfo

func (m *ConsumerSpec_ReceiverQueueSize) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type SourceSpec struct {
	ClassName string `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`
	// map in json format
	Configs       string `protobuf:"bytes,2,opt,name=configs,proto3" json:"configs,omitempty"`
	TypeClassName string `protobuf:"bytes,5,opt,name=typeClassName,proto3" json:"typeClassName,omitempty"`
	// configs used only when source feeds into functions
	SubscriptionType SubscriptionType `protobuf:"varint,3,opt,name=subscriptionType,proto3,enum=proto.SubscriptionType" json:"subscriptionType,omitempty"`
	// @deprecated -- use topicsToSchema
	TopicsToSerDeClassName map[string]string `protobuf:"bytes,4,rep,name=topicsToSerDeClassName,proto3" json:"topicsToSerDeClassName,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Deprecated: Do not use.
	// *
	//
	InputSpecs    map[string]*ConsumerSpec `protobuf:"bytes,10,rep,name=inputSpecs,proto3" json:"inputSpecs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TimeoutMs     uint64                   `protobuf:"varint,6,opt,name=timeoutMs,proto3" json:"timeoutMs,omitempty"`
	TopicsPattern string                   `protobuf:"bytes,7,opt,name=topicsPattern,proto3" json:"topicsPattern,omitempty"` // Deprecated: Do not use.
	// If specified, this will refer to an archive that is
	// already present in the server
	Builtin              string               `protobuf:"bytes,8,opt,name=builtin,proto3" json:"builtin,omitempty"`
	SubscriptionName     string               `protobuf:"bytes,9,opt,name=subscriptionName,proto3" json:"subscriptionName,omitempty"`
	CleanupSubscription  bool                 `protobuf:"varint,11,opt,name=cleanupSubscription,proto3" json:"cleanupSubscription,omitempty"`
	SubscriptionPosition SubscriptionPosition `protobuf:"varint,12,opt,name=subscriptionPosition,proto3,enum=proto.SubscriptionPosition" json:"subscriptionPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SourceSpec) Reset()         { *m = SourceSpec{} }
func (m *SourceSpec) String() string { return proto.CompactTextString(m) }
func (*SourceSpec) ProtoMessage()    {}
func (*SourceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{4}
}
func (m *SourceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceSpec.Unmarshal(m, b)
}
func (m *SourceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceSpec.Marshal(b, m, deterministic)
}
func (dst *SourceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceSpec.Merge(dst, src)
}
func (m *SourceSpec) XXX_Size() int {
	return xxx_messageInfo_SourceSpec.Size(m)
}
func (m *SourceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SourceSpec proto.InternalMessageInfo

func (m *SourceSpec) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *SourceSpec) GetConfigs() string {
	if m != nil {
		return m.Configs
	}
	return ""
}

func (m *SourceSpec) GetTypeClassName() string {
	if m != nil {
		return m.TypeClassName
	}
	return ""
}

func (m *SourceSpec) GetSubscriptionType() SubscriptionType {
	if m != nil {
		return m.SubscriptionType
	}
	return SubscriptionType_SHARED
}

// Deprecated: Do not use.
func (m *SourceSpec) GetTopicsToSerDeClassName() map[string]string {
	if m != nil {
		return m.TopicsToSerDeClassName
	}
	return nil
}

func (m *SourceSpec) GetInputSpecs() map[string]*ConsumerSpec {
	if m != nil {
		return m.InputSpecs
	}
	return nil
}

func (m *SourceSpec) GetTimeoutMs() uint64 {
	if m != nil {
		return m.TimeoutMs
	}
	return 0
}

// Deprecated: Do not use.
func (m *SourceSpec) GetTopicsPattern() string {
	if m != nil {
		return m.TopicsPattern
	}
	return ""
}

func (m *SourceSpec) GetBuiltin() string {
	if m != nil {
		return m.Builtin
	}
	return ""
}

func (m *SourceSpec) GetSubscriptionName() string {
	if m != nil {
		return m.SubscriptionName
	}
	return ""
}

func (m *SourceSpec) GetCleanupSubscription() bool {
	if m != nil {
		return m.CleanupSubscription
	}
	return false
}

func (m *SourceSpec) GetSubscriptionPosition() SubscriptionPosition {
	if m != nil {
		return m.SubscriptionPosition
	}
	return SubscriptionPosition_LATEST
}

type SinkSpec struct {
	ClassName string `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`
	// map in json format
	Configs       string `protobuf:"bytes,2,opt,name=configs,proto3" json:"configs,omitempty"`
	TypeClassName string `protobuf:"bytes,5,opt,name=typeClassName,proto3" json:"typeClassName,omitempty"`
	// configs used only when functions output to sink
	Topic          string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	SerDeClassName string `protobuf:"bytes,4,opt,name=serDeClassName,proto3" json:"serDeClassName,omitempty"`
	// If specified, this will refer to an archive that is
	// already present in the server
	Builtin string `protobuf:"bytes,6,opt,name=builtin,proto3" json:"builtin,omitempty"`
	// *
	// Builtin schema type or custom schema class name
	SchemaType                   string   `protobuf:"bytes,7,opt,name=schemaType,proto3" json:"schemaType,omitempty"`
	ForwardSourceMessageProperty bool     `protobuf:"varint,8,opt,name=forwardSourceMessageProperty,proto3" json:"forwardSourceMessageProperty,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *SinkSpec) Reset()         { *m = SinkSpec{} }
func (m *SinkSpec) String() string { return proto.CompactTextString(m) }
func (*SinkSpec) ProtoMessage()    {}
func (*SinkSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{5}
}
func (m *SinkSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinkSpec.Unmarshal(m, b)
}
func (m *SinkSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinkSpec.Marshal(b, m, deterministic)
}
func (dst *SinkSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinkSpec.Merge(dst, src)
}
func (m *SinkSpec) XXX_Size() int {
	return xxx_messageInfo_SinkSpec.Size(m)
}
func (m *SinkSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SinkSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SinkSpec proto.InternalMessageInfo

func (m *SinkSpec) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *SinkSpec) GetConfigs() string {
	if m != nil {
		return m.Configs
	}
	return ""
}

func (m *SinkSpec) GetTypeClassName() string {
	if m != nil {
		return m.TypeClassName
	}
	return ""
}

func (m *SinkSpec) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SinkSpec) GetSerDeClassName() string {
	if m != nil {
		return m.SerDeClassName
	}
	return ""
}

func (m *SinkSpec) GetBuiltin() string {
	if m != nil {
		return m.Builtin
	}
	return ""
}

func (m *SinkSpec) GetSchemaType() string {
	if m != nil {
		return m.SchemaType
	}
	return ""
}

func (m *SinkSpec) GetForwardSourceMessageProperty() bool {
	if m != nil {
		return m.ForwardSourceMessageProperty
	}
	return false
}

type PackageLocationMetaData struct {
	PackagePath          string   `protobuf:"bytes,1,opt,name=packagePath,proto3" json:"packagePath,omitempty"`
	OriginalFileName     string   `protobuf:"bytes,2,opt,name=originalFileName,proto3" json:"originalFileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageLocationMetaData) Reset()         { *m = PackageLocationMetaData{} }
func (m *PackageLocationMetaData) String() string { return proto.CompactTextString(m) }
func (*PackageLocationMetaData) ProtoMessage()    {}
func (*PackageLocationMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{6}
}
func (m *PackageLocationMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageLocationMetaData.Unmarshal(m, b)
}
func (m *PackageLocationMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageLocationMetaData.Marshal(b, m, deterministic)
}
func (dst *PackageLocationMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageLocationMetaData.Merge(dst, src)
}
func (m *PackageLocationMetaData) XXX_Size() int {
	return xxx_messageInfo_PackageLocationMetaData.Size(m)
}
func (m *PackageLocationMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageLocationMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_PackageLocationMetaData proto.InternalMessageInfo

func (m *PackageLocationMetaData) GetPackagePath() string {
	if m != nil {
		return m.PackagePath
	}
	return ""
}

func (m *PackageLocationMetaData) GetOriginalFileName() string {
	if m != nil {
		return m.OriginalFileName
	}
	return ""
}

type FunctionMetaData struct {
	FunctionDetails      *FunctionDetails            `protobuf:"bytes,1,opt,name=functionDetails,proto3" json:"functionDetails,omitempty"`
	PackageLocation      *PackageLocationMetaData    `protobuf:"bytes,2,opt,name=packageLocation,proto3" json:"packageLocation,omitempty"`
	Version              uint64                      `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	CreateTime           uint64                      `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	InstanceStates       map[int32]FunctionState     `protobuf:"bytes,5,rep,name=instanceStates,proto3" json:"instanceStates,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=proto.FunctionState"`
	FunctionAuthSpec     *FunctionAuthenticationSpec `protobuf:"bytes,6,opt,name=functionAuthSpec,proto3" json:"functionAuthSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FunctionMetaData) Reset()         { *m = FunctionMetaData{} }
func (m *FunctionMetaData) String() string { return proto.CompactTextString(m) }
func (*FunctionMetaData) ProtoMessage()    {}
func (*FunctionMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{7}
}
func (m *FunctionMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionMetaData.Unmarshal(m, b)
}
func (m *FunctionMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionMetaData.Marshal(b, m, deterministic)
}
func (dst *FunctionMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionMetaData.Merge(dst, src)
}
func (m *FunctionMetaData) XXX_Size() int {
	return xxx_messageInfo_FunctionMetaData.Size(m)
}
func (m *FunctionMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionMetaData proto.InternalMessageInfo

func (m *FunctionMetaData) GetFunctionDetails() *FunctionDetails {
	if m != nil {
		return m.FunctionDetails
	}
	return nil
}

func (m *FunctionMetaData) GetPackageLocation() *PackageLocationMetaData {
	if m != nil {
		return m.PackageLocation
	}
	return nil
}

func (m *FunctionMetaData) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FunctionMetaData) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *FunctionMetaData) GetInstanceStates() map[int32]FunctionState {
	if m != nil {
		return m.InstanceStates
	}
	return nil
}

func (m *FunctionMetaData) GetFunctionAuthSpec() *FunctionAuthenticationSpec {
	if m != nil {
		return m.FunctionAuthSpec
	}
	return nil
}

type FunctionAuthenticationSpec struct {
	// *
	// function authentication related data that the function authentication provider
	// needs to cache/distribute to all workers support function authentication.
	// Depending on the function authentication provider implementation, this can be the actual auth credentials
	// or a pointer to the auth credentials that this function should use
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// *
	// classname of the function auth provicer this data is relevant to
	Provider             string   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionAuthenticationSpec) Reset()         { *m = FunctionAuthenticationSpec{} }
func (m *FunctionAuthenticationSpec) String() string { return proto.CompactTextString(m) }
func (*FunctionAuthenticationSpec) ProtoMessage()    {}
func (*FunctionAuthenticationSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{8}
}
func (m *FunctionAuthenticationSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionAuthenticationSpec.Unmarshal(m, b)
}
func (m *FunctionAuthenticationSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionAuthenticationSpec.Marshal(b, m, deterministic)
}
func (dst *FunctionAuthenticationSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionAuthenticationSpec.Merge(dst, src)
}
func (m *FunctionAuthenticationSpec) XXX_Size() int {
	return xxx_messageInfo_FunctionAuthenticationSpec.Size(m)
}
func (m *FunctionAuthenticationSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionAuthenticationSpec.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionAuthenticationSpec proto.InternalMessageInfo

func (m *FunctionAuthenticationSpec) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FunctionAuthenticationSpec) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type Instance struct {
	FunctionMetaData     *FunctionMetaData `protobuf:"bytes,1,opt,name=functionMetaData,proto3" json:"functionMetaData,omitempty"`
	InstanceId           int32             `protobuf:"varint,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{9}
}
func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (dst *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(dst, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetFunctionMetaData() *FunctionMetaData {
	if m != nil {
		return m.FunctionMetaData
	}
	return nil
}

func (m *Instance) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type Assignment struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	WorkerId             string    `protobuf:"bytes,2,opt,name=workerId,proto3" json:"workerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Assignment) Reset()         { *m = Assignment{} }
func (m *Assignment) String() string { return proto.CompactTextString(m) }
func (*Assignment) ProtoMessage()    {}
func (*Assignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_Function_b30b40f847baaf25, []int{10}
}
func (m *Assignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assignment.Unmarshal(m, b)
}
func (m *Assignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assignment.Marshal(b, m, deterministic)
}
func (dst *Assignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assignment.Merge(dst, src)
}
func (m *Assignment) XXX_Size() int {
	return xxx_messageInfo_Assignment.Size(m)
}
func (m *Assignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Assignment.DiscardUnknown(m)
}

var xxx_messageInfo_Assignment proto.InternalMessageInfo

func (m *Assignment) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *Assignment) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

func init() {
	proto.RegisterType((*Resources)(nil), "proto.Resources")
	proto.RegisterType((*RetryDetails)(nil), "proto.RetryDetails")
	proto.RegisterType((*FunctionDetails)(nil), "proto.FunctionDetails")
	proto.RegisterType((*ConsumerSpec)(nil), "proto.ConsumerSpec")
	proto.RegisterType((*ConsumerSpec_ReceiverQueueSize)(nil), "proto.ConsumerSpec.ReceiverQueueSize")
	proto.RegisterType((*SourceSpec)(nil), "proto.SourceSpec")
	proto.RegisterMapType((map[string]*ConsumerSpec)(nil), "proto.SourceSpec.InputSpecsEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.SourceSpec.TopicsToSerDeClassNameEntry")
	proto.RegisterType((*SinkSpec)(nil), "proto.SinkSpec")
	proto.RegisterType((*PackageLocationMetaData)(nil), "proto.PackageLocationMetaData")
	proto.RegisterType((*FunctionMetaData)(nil), "proto.FunctionMetaData")
	proto.RegisterMapType((map[int32]FunctionState)(nil), "proto.FunctionMetaData.InstanceStatesEntry")
	proto.RegisterType((*FunctionAuthenticationSpec)(nil), "proto.FunctionAuthenticationSpec")
	proto.RegisterType((*Instance)(nil), "proto.Instance")
	proto.RegisterType((*Assignment)(nil), "proto.Assignment")
	proto.RegisterEnum("proto.ProcessingGuarantees", ProcessingGuarantees_name, ProcessingGuarantees_value)
	proto.RegisterEnum("proto.SubscriptionType", SubscriptionType_name, SubscriptionType_value)
	proto.RegisterEnum("proto.SubscriptionPosition", SubscriptionPosition_name, SubscriptionPosition_value)
	proto.RegisterEnum("proto.FunctionState", FunctionState_name, FunctionState_value)
	proto.RegisterEnum("proto.FunctionDetails_Runtime", FunctionDetails_Runtime_name, FunctionDetails_Runtime_value)
	proto.RegisterEnum("proto.FunctionDetails_ComponentType", FunctionDetails_ComponentType_name, FunctionDetails_ComponentType_value)
}

func init() { proto.RegisterFile("Function.proto", fileDescriptor_Function_b30b40f847baaf25) }

var fileDescriptor_Function_b30b40f847baaf25 = []byte{
	// 1438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x6f, 0xdb, 0x36,
	0x17, 0x8e, 0xe2, 0xf8, 0xeb, 0xd8, 0x89, 0x15, 0xc6, 0x68, 0x85, 0xb4, 0x28, 0x52, 0xbf, 0x7d,
	0x37, 0x27, 0x6d, 0x8d, 0x22, 0xbb, 0x58, 0xb1, 0xab, 0x3a, 0x8e, 0xd3, 0xba, 0x75, 0x6c, 0x8f,
	0x56, 0x5a, 0xf4, 0x6a, 0x60, 0x15, 0xc6, 0x21, 0x22, 0x4b, 0x02, 0x49, 0xa5, 0xcd, 0xae, 0x77,
	0xbb, 0x7f, 0xb1, 0xbf, 0xb4, 0xbf, 0x33, 0x0c, 0xa4, 0x24, 0x5b, 0x92, 0x9d, 0xde, 0xed, 0x4a,
	0x3a, 0xcf, 0xf9, 0x22, 0x0f, 0x9f, 0x73, 0x48, 0xd8, 0x39, 0x0b, 0x3d, 0x47, 0x32, 0xdf, 0xeb,
	0x04, 0xdc, 0x97, 0x3e, 0x2a, 0xea, 0x4f, 0xab, 0x07, 0x55, 0x4c, 0x85, 0x1f, 0x72, 0x87, 0x0a,
	0x64, 0x42, 0xc1, 0x09, 0x42, 0xcb, 0x38, 0x30, 0xda, 0x06, 0x56, 0xbf, 0x0a, 0xe1, 0x64, 0x6e,
	0x6d, 0x1e, 0x18, 0xed, 0x02, 0x56, 0xbf, 0x08, 0xc1, 0xd6, 0x25, 0x13, 0x37, 0x56, 0x41, 0x43,
	0xfa, 0xbf, 0x75, 0x05, 0x75, 0x4c, 0x25, 0xbf, 0x3b, 0xa5, 0x92, 0x30, 0x57, 0xa0, 0x17, 0xb0,
	0x3b, 0x27, 0xdf, 0xce, 0xa9, 0x10, 0x64, 0x46, 0x95, 0x86, 0x51, 0xa1, 0xa3, 0x16, 0xf1, 0xaa,
	0x02, 0xb5, 0xa1, 0x71, 0x49, 0xc9, 0xe5, 0x90, 0x4a, 0x49, 0xb9, 0xed, 0x07, 0xcc, 0xd1, 0xf9,
	0xaa, 0x38, 0x0f, 0xb7, 0xfe, 0x28, 0x43, 0x23, 0xd9, 0x46, 0x92, 0xeb, 0x01, 0x94, 0x24, 0xf5,
	0x88, 0x27, 0x75, 0x82, 0x2a, 0x8e, 0x25, 0xf4, 0x18, 0xaa, 0x1e, 0x99, 0x53, 0x11, 0x10, 0x87,
	0xc6, 0xf1, 0x96, 0x80, 0xda, 0x85, 0x12, 0xf4, 0x2e, 0xaa, 0x58, 0xff, 0x2b, 0x0f, 0xc7, 0x25,
	0x42, 0x8c, 0x94, 0x62, 0x2b, 0xf2, 0x58, 0x00, 0x68, 0x1f, 0x2a, 0xae, 0x3f, 0x8b, 0x96, 0x57,
	0xd4, 0xca, 0x85, 0x8c, 0xc6, 0xd0, 0x0c, 0xb8, 0xef, 0x50, 0x21, 0x98, 0x37, 0x7b, 0x1b, 0x12,
	0x4e, 0x3c, 0x49, 0xa9, 0xb0, 0x4a, 0x07, 0x46, 0x7b, 0xe7, 0xf8, 0x51, 0x54, 0xf1, 0xce, 0x64,
	0x8d, 0x09, 0x5e, 0xeb, 0x88, 0x9e, 0x00, 0x84, 0x82, 0xf2, 0x9e, 0xef, 0x5d, 0xb1, 0x99, 0x55,
	0xd6, 0xe9, 0x52, 0x88, 0xd2, 0x0b, 0xea, 0x70, 0x2a, 0xc5, 0x39, 0x09, 0x2c, 0x33, 0xd2, 0x2f,
	0x11, 0xf4, 0x1a, 0xca, 0x3c, 0xf4, 0x24, 0x9b, 0x53, 0xab, 0xa2, 0xd7, 0xf0, 0x24, 0x5e, 0x43,
	0xae, 0x7a, 0x1d, 0x1c, 0x59, 0xe1, 0xc4, 0x1c, 0x59, 0x50, 0x26, 0xa1, 0xf4, 0xbb, 0xce, 0x8d,
	0x55, 0x3d, 0x30, 0xda, 0x15, 0x9c, 0x88, 0xe8, 0x00, 0x6a, 0x01, 0xe1, 0xc4, 0x75, 0xa9, 0xcb,
	0xc4, 0xdc, 0x02, 0x7d, 0x9c, 0x69, 0x08, 0x1d, 0x42, 0x29, 0x62, 0x92, 0x55, 0x3b, 0x30, 0xda,
	0xb5, 0xe3, 0xdd, 0x38, 0xe9, 0x54, 0x83, 0xd3, 0x80, 0x3a, 0x38, 0x36, 0x40, 0xff, 0x83, 0x2d,
	0xc1, 0xbc, 0x1b, 0xab, 0xae, 0x0d, 0x1b, 0x89, 0x21, 0xf3, 0x6e, 0xb4, 0x99, 0x56, 0xa2, 0x0e,
	0x54, 0x79, 0xc2, 0x4d, 0x6b, 0x5b, 0x5b, 0x9a, 0xb1, 0xe5, 0x82, 0xb3, 0x78, 0x69, 0xa2, 0xaa,
	0x12, 0x10, 0xe7, 0x86, 0xcc, 0xe8, 0x05, 0x77, 0xad, 0x9d, 0xa8, 0x2a, 0x4b, 0x04, 0xfd, 0x0c,
	0x75, 0x9e, 0xa2, 0xa9, 0xd5, 0xd0, 0x21, 0xf7, 0x16, 0x21, 0x97, 0x2a, 0x9c, 0x31, 0x44, 0x2d,
	0xa8, 0xc7, 0xf5, 0x39, 0x73, 0xc9, 0x4c, 0x58, 0xbb, 0x3a, 0x74, 0x06, 0x43, 0xef, 0x61, 0xdb,
	0xf1, 0xe7, 0x81, 0xef, 0x51, 0x4f, 0xda, 0x77, 0x01, 0xb5, 0x90, 0x2e, 0xfc, 0xb3, 0x7b, 0x0a,
	0xdf, 0x4b, 0xdb, 0xe2, 0xac, 0x2b, 0x3a, 0x86, 0xa6, 0x13, 0x0a, 0xe9, 0xcf, 0xe3, 0xe3, 0x19,
	0x07, 0xca, 0x55, 0x58, 0x7b, 0x3a, 0xef, 0x5a, 0x5d, 0xeb, 0x47, 0x28, 0xc7, 0x08, 0xaa, 0xc0,
	0xd6, 0xfb, 0xee, 0xc7, 0xae, 0xb9, 0x81, 0x00, 0x4a, 0x93, 0xcf, 0xf6, 0xbb, 0xf1, 0xc8, 0x34,
	0x50, 0x09, 0x36, 0xdf, 0x8e, 0xcd, 0x42, 0xeb, 0x0d, 0x6c, 0x67, 0x92, 0xa3, 0x1a, 0x94, 0x2f,
	0x46, 0x1f, 0x46, 0xe3, 0x4f, 0x23, 0x73, 0x03, 0xd5, 0xa1, 0x72, 0x76, 0x31, 0xea, 0xd9, 0x03,
	0xed, 0x03, 0x50, 0x9a, 0x8e, 0x2f, 0x70, 0xaf, 0x6f, 0x6e, 0xaa, 0xa8, 0xd3, 0xc1, 0xe8, 0x83,
	0x59, 0x68, 0xfd, 0x63, 0x40, 0xbd, 0xe7, 0x7b, 0x22, 0x9c, 0x53, 0xae, 0x8e, 0x4b, 0xd3, 0xd1,
	0xb9, 0xa6, 0x73, 0xa2, 0x37, 0x6e, 0xc4, 0x74, 0x5c, 0x20, 0xe8, 0x07, 0xd8, 0x11, 0x94, 0x5f,
	0xd2, 0xde, 0xa2, 0xbd, 0xa2, 0x86, 0xcc, 0xa1, 0xca, 0x8e, 0x09, 0x4c, 0x67, 0xf4, 0xdb, 0x84,
	0xa8, 0xae, 0xf7, 0x74, 0x7f, 0x56, 0x70, 0x0e, 0x45, 0x53, 0xd8, 0xe5, 0xd4, 0xa1, 0xec, 0x96,
	0xf2, 0x5f, 0x43, 0x1a, 0xd2, 0x29, 0xfb, 0x3d, 0xea, 0xd8, 0xda, 0xf1, 0xff, 0xe3, 0x7a, 0xa7,
	0xd7, 0xd7, 0xc1, 0x79, 0x63, 0xbc, 0xea, 0xbf, 0x7f, 0x08, 0xbb, 0x2b, 0x76, 0xa8, 0x09, 0xc5,
	0x5b, 0xe2, 0x86, 0x34, 0x9e, 0x5e, 0x91, 0xd0, 0xfa, 0xb3, 0x04, 0xb0, 0x24, 0x75, 0x76, 0x70,
	0x18, 0xf9, 0xc1, 0x61, 0x41, 0xd9, 0xd1, 0x5d, 0x2b, 0xe2, 0x5d, 0x27, 0x22, 0x7a, 0x06, 0xdb,
	0xf2, 0x2e, 0x48, 0x55, 0x25, 0x9a, 0x2b, 0x59, 0x10, 0xf5, 0xc0, 0x14, 0xe1, 0x17, 0xe1, 0x70,
	0xa6, 0x4f, 0x5a, 0x97, 0xb8, 0xa0, 0xb9, 0xf5, 0x30, 0x69, 0x9b, 0x9c, 0x1a, 0xaf, 0x38, 0x20,
	0x06, 0x0f, 0xa4, 0x1a, 0x55, 0xc2, 0xf6, 0xa7, 0x94, 0x9f, 0xa6, 0x72, 0x6e, 0x1d, 0x14, 0xda,
	0xb5, 0xe3, 0x97, 0x2b, 0xad, 0xda, 0xb1, 0xd7, 0xda, 0xf7, 0x3d, 0xc9, 0xef, 0x4e, 0x36, 0x2d,
	0x03, 0xdf, 0x13, 0x10, 0x75, 0x01, 0x98, 0x17, 0x84, 0x52, 0x05, 0x11, 0x16, 0xe8, 0xf0, 0x4f,
	0x57, 0xc3, 0x0f, 0x16, 0x36, 0x3a, 0x24, 0x4e, 0x39, 0xa9, 0x82, 0x2a, 0x22, 0xfb, 0xa1, 0x3c,
	0x8f, 0x86, 0xe8, 0x16, 0x5e, 0x02, 0xa8, 0x0d, 0xdb, 0x51, 0xea, 0x84, 0x24, 0x7a, 0x3e, 0xea,
	0x35, 0x65, 0x15, 0xaa, 0xf4, 0x5f, 0x42, 0xe6, 0x4a, 0xe6, 0xe9, 0x31, 0x58, 0xc5, 0x89, 0x88,
	0x8e, 0xb2, 0x45, 0xd5, 0x95, 0xa8, 0x6a, 0x93, 0x15, 0x1c, 0xbd, 0x82, 0x3d, 0xc7, 0xa5, 0xc4,
	0x0b, 0x83, 0x74, 0xa1, 0xf5, 0x8c, 0xab, 0xe0, 0x75, 0x2a, 0x75, 0x1f, 0xa4, 0xa3, 0x4c, 0x7c,
	0xc1, 0xb4, 0x4b, 0x3d, 0x73, 0x1f, 0x4c, 0xd7, 0x98, 0xe0, 0xb5, 0x8e, 0xfb, 0x03, 0x78, 0xf4,
	0x9d, 0xe3, 0x50, 0xb7, 0xf4, 0x0d, 0xbd, 0x8b, 0xa9, 0xa7, 0x7e, 0x97, 0xbc, 0x8d, 0x28, 0x17,
	0x09, 0xbf, 0x6c, 0xbe, 0x36, 0xf6, 0x31, 0x34, 0x72, 0xa5, 0x5f, 0xe3, 0x7e, 0x98, 0x76, 0x5f,
	0x8e, 0xc8, 0x74, 0x53, 0xa5, 0x62, 0xb6, 0xfe, 0xda, 0x84, 0x4a, 0x32, 0xbb, 0xff, 0xe3, 0x6e,
	0x68, 0x42, 0x51, 0x9f, 0x71, 0x7c, 0x73, 0x47, 0x42, 0x3c, 0x60, 0xb2, 0xb4, 0x4e, 0x06, 0x4c,
	0x9a, 0x9b, 0x29, 0x42, 0x94, 0xb2, 0x84, 0xc8, 0x8e, 0xb0, 0xf2, 0xca, 0x08, 0x3b, 0x81, 0xc7,
	0x57, 0x3e, 0xff, 0x4a, 0xf8, 0x65, 0xc4, 0xe1, 0xf8, 0x0d, 0x33, 0xe1, 0x7e, 0x40, 0xb9, 0xbc,
	0xd3, 0xfc, 0xaa, 0xe0, 0xef, 0xda, 0xb4, 0x66, 0xf0, 0x70, 0x12, 0xdd, 0x46, 0x43, 0xdf, 0x21,
	0xea, 0x60, 0xcf, 0xa9, 0x24, 0xa7, 0x44, 0x92, 0xe8, 0x72, 0xd5, 0xaa, 0x09, 0x91, 0xd7, 0x71,
	0xd9, 0xd2, 0x90, 0x62, 0xac, 0xcf, 0xd9, 0x8c, 0x79, 0xc4, 0x3d, 0x63, 0x2e, 0x4d, 0x4d, 0xd1,
	0x15, 0xbc, 0xf5, 0x77, 0x01, 0xcc, 0xe4, 0xc2, 0x59, 0xa4, 0x78, 0x03, 0x8d, 0xab, 0xec, 0x25,
	0xa4, 0xd3, 0xd4, 0x8e, 0x1f, 0xac, 0xbf, 0xa2, 0x70, 0xde, 0x1c, 0xbd, 0x83, 0x46, 0x90, 0x5d,
	0x7f, 0xcc, 0x8f, 0xe4, 0x75, 0x71, 0xcf, 0xee, 0x70, 0xde, 0x4d, 0x9d, 0xc3, 0x2d, 0xe5, 0x42,
	0x45, 0x28, 0xe8, 0xf6, 0x4e, 0x44, 0x75, 0x0e, 0x0e, 0xa7, 0x44, 0x52, 0x9b, 0xc5, 0xa7, 0xb8,
	0x85, 0x53, 0x08, 0x9a, 0xc2, 0x0e, 0xf3, 0x84, 0x24, 0x9e, 0x43, 0xa7, 0x92, 0x48, 0x2a, 0xac,
	0xa2, 0x9e, 0x30, 0xcf, 0x73, 0x9b, 0x48, 0x72, 0x77, 0x06, 0x19, 0xeb, 0x68, 0xd6, 0xe4, 0x42,
	0xa0, 0x73, 0x30, 0x93, 0xbd, 0x76, 0x43, 0x79, 0xad, 0x68, 0xac, 0xf9, 0xb1, 0x1c, 0x5c, 0x67,
	0x29, 0x35, 0xf5, 0x24, 0x8b, 0xf6, 0xa1, 0xfb, 0x60, 0xc5, 0x75, 0xff, 0x13, 0xec, 0xad, 0xc9,
	0x9a, 0x6e, 0xb3, 0x62, 0xd4, 0x66, 0x47, 0xe9, 0x36, 0xdb, 0x39, 0x6e, 0xe6, 0x92, 0x69, 0xe7,
	0x74, 0x9f, 0x0d, 0x61, 0xff, 0xfe, 0x85, 0xe8, 0x97, 0x39, 0x91, 0x44, 0x27, 0xa8, 0x63, 0xfd,
	0xaf, 0x5e, 0xad, 0x01, 0xf7, 0x6f, 0xd9, 0x25, 0xe5, 0x31, 0x5b, 0x16, 0x72, 0xcb, 0x87, 0x4a,
	0xb2, 0x4c, 0x75, 0xc9, 0x5c, 0xe5, 0x2a, 0x17, 0xb3, 0xe3, 0xe1, 0x3d, 0x85, 0xc5, 0x2b, 0x0e,
	0xea, 0xec, 0x92, 0xc2, 0x0e, 0x2e, 0x75, 0xba, 0x22, 0x4e, 0x21, 0xad, 0x0b, 0x80, 0xae, 0x10,
	0x6c, 0xe6, 0xcd, 0xa9, 0x27, 0xd1, 0x73, 0xa8, 0x24, 0xba, 0x38, 0x55, 0xf2, 0x0c, 0x4c, 0x56,
	0x85, 0x17, 0x06, 0x6a, 0x1f, 0x5f, 0x7d, 0x7e, 0x43, 0x79, 0x1c, 0xb8, 0x8a, 0x17, 0xf2, 0xd1,
	0x18, 0x9a, 0xeb, 0x9e, 0xd6, 0xc8, 0x84, 0x7a, 0xd7, 0x1e, 0xf6, 0xbb, 0x53, 0xfb, 0xb7, 0xf1,
	0xa8, 0xd7, 0x37, 0x37, 0x50, 0x03, 0x6a, 0x5d, 0xfb, 0x7c, 0x9c, 0x00, 0x06, 0x6a, 0x82, 0xd9,
	0x3f, 0x3b, 0xeb, 0xf7, 0xec, 0xc1, 0xc7, 0xfe, 0xf0, 0x73, 0x84, 0x6e, 0x1e, 0xbd, 0x00, 0x33,
	0x7f, 0xa5, 0xea, 0x97, 0xd0, 0xbb, 0x2e, 0xee, 0x9f, 0xc6, 0x6f, 0xa4, 0xee, 0x60, 0x38, 0xfe,
	0xd8, 0xc7, 0xa6, 0x71, 0xf4, 0x0a, 0x9a, 0xeb, 0x26, 0xb9, 0xf2, 0x18, 0x76, 0xed, 0xfe, 0xd4,
	0x8e, 0x3c, 0xfa, 0x5d, 0x3c, 0x1c, 0x28, 0xc9, 0x38, 0x3a, 0x84, 0xed, 0xcc, 0x11, 0xab, 0x17,
	0x18, 0xbe, 0x18, 0x8d, 0x06, 0xa3, 0xb7, 0xe6, 0x86, 0x12, 0xa6, 0xf6, 0x78, 0x32, 0xe9, 0x9f,
	0x9a, 0xc6, 0xc9, 0x4b, 0x78, 0xea, 0xf3, 0x59, 0x87, 0x04, 0xc4, 0xb9, 0xa6, 0x9d, 0x20, 0x74,
	0x05, 0xe1, 0x9d, 0xa4, 0xf0, 0x22, 0xaa, 0xd7, 0x49, 0x25, 0x89, 0xf6, 0xa5, 0xa4, 0x81, 0x9f,
	0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xe8, 0x5e, 0x7f, 0xed, 0x0d, 0x00, 0x00,
}
