name: CI - Unit - Brokers
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:

  unit-tests:
    name:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: checkout
        uses: actions/checkout@v1

      - name: Set up Maven
        uses: aahmed-se/setup-maven@v3
        with:
          maven-version: 3.6.1

      - name: run unit tests install by skip tests
        run: mvn clean install -DskipTests

      - name: run unit tests pulsar broker reader test
        run: mvn test -DfailIfNoTests=false '-Dtest=ReaderTest' -pl pulsar-broker

      - name: run unit tests pulsar broker rack aware test
        run: mvn test -DfailIfNoTests=false '-Dtest=RackAwareTest' -pl pulsar-broker

      - name: run unit test pulsar-broker
        run: mvn test '-Dtest=!PersistentTransactionBufferTest,!PulsarFunctionE2ESecurityTest,!ServerCnxTest,!AdminApiOffloadTest,!AdminApiSchemaValidationEnforced,!V1_AdminApiTest2,!ProxyPublishConsumeTlsTest,!PulsarFunctionE2ETest,!MessageIdSerialization,!AdminApiTest2,!PulsarFunctionLocalRunTest,!PartitionedProducerConsumerTest,!KafkaProducerSimpleConsumerTest,!ProxyTest,!MessagePublishThrottlingTest,!ReaderTest,!RackAwareTest' -DfailIfNoTests=false -pl pulsar-broker
