name: CI - Unit - Adaptors
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:

  unit-tests:
    name:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: checkout
        uses: actions/checkout@v1

      - name: Set up Maven
        uses: aahmed-se/setup-maven@v3
        with:
          maven-version: 3.6.1

      - name: run unit tests install by skip tests
        run: mvn clean install -DskipTests

      - name: run unit tests pulsar io kafka connect adaptor
        run: mvn test -pl pulsar-io/kafka-connect-adaptor

      - name: run unit tests pulsar storm tests
        run: mvn test -pl tests/pulsar-storm-test
